name: deploy to github pages.

on:
  push:
    branches:
      - master
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3 
        with: 
          node-version: '24'

      - name: Install packages
        run: npm ci 
      
      - name: Build 
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: dist/gzg-money/browser
          branch: gh-pages